apiVersion: v1
kind: Service
metadata:
  name: three-tier-app-back-service
spec:
  selector:
    app: three-tier-back-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007  # Correct indentation
  type: LoadBalancer

