apiVersion: v1
kind: Service
metadata:
  name: three-tier-app-service
spec:
  selector:
    app: three-tier-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30004
  type: LoadBalancer

